# 基本配置
data:
  file_path: 'data/USDJPY.csv'
  date_column: 'Date'
  value_column: 'Close'

# 数据处理配置
preprocessing:
  frequency: '10T'
  fill_method: 'ffill'
  drop_minutes: [15, 45]

# 分析配置
analysis:
  stationarity:
    test_method: 'adf'  # 'adf' or 'kpss'
    significance_level: 0.05
  differencing:
    max_order: 2

# 建模配置
modeling:
  ar:
    max_lag: 20
  ma:
    max_order: 5
  arima:
    p_range: [0, 6]
    d_range: [0, 3]
    q_range: [0, 6]

# 可视化配置
visualization:
  plot_acf_pacf:
    lags: 40
  plot_results:
    figsize: [12, 8]

# 高级分析配置
advanced_analysis:
  stl:
    period: 144
    seasonal: 7
  mstl:
    seasonal_periods: [144, 1008, 52560]
    n_jobs: 4

# 输出配置
output:
  save_plots: true
  plot_directory: 'output/plots'
  save_results: true
  results_file: 'output/analysis_results.json'

# 日志配置
logging:
  level: 'INFO'
  file: 'logs/tsanalysis.log'